#!/bin/sh

matches=$(git diff  --cached -- . ':!*pre-commit' -- . ':!*README.md' | grep -E '\+.*?(TODO|FIXME)')

if [ "$matches" != "" ]
then
        echo "'TODO' or 'FIXME' tag is detected."
        echo "Please fix it before committing."
        echo "  ${matches}"
        exit 1
fi
