#!/bin/sh

lines=$(git diff  --cached -- . ':!*pre-commit' -- . ':!*README.md' | grep -E '\+.*?(TODO|FIXME)')

if [ "$lines" != "" ]
then
        echo "\033[31m 'TODO' or 'FIXME' comments detected."
        echo "\033[31m Please resolve it before committing."
        echo "  ${lines}"
        exit 1
fi
